<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Table to show the list of programs available for SEB.
 *
 * @package    local_sebprogram
 * @copyright  2024 Universidad de Málaga
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
namespace local_sebprogram\local\table;

use local_sebprogram\program;
use local_sebprogram\program_manager;
defined('MOODLE_INTERNAL') || die();

require_once($CFG->libdir . '/tablelib.php');

/**
 * Table to show the list of programs available for SEB.
 *
 * @package    local_sebprogram
 * @copyright  2024 Universidad de Málaga
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class program_list extends \flexible_table {
    /**
     * @var int Autogenerated id.
     */
    private static $autoid = 0;

    /**
     * @var int Course module id of the activity to continue editing after returning
     */
    private $returncmid = 0;

    /**
     * Constructor
     *
     * @param string|null $id to be used by the table, autogenerated if null.
     * @param \context $context The system or user context
     * @param array $hiddencolumns Columns to hide
     * @param bool $sortable Sorting the table
     */
    public function __construct(string|null $id, \context $context, ?array $hiddencolumns = null, $sortable = true) {
        global $PAGE;

        $id = (is_null($id) ? self::$autoid++ : $id);
        parent::__construct('local_sebprogram' . $id);

        $this->define_baseurl($PAGE->url);
        $this->set_attribute('class', 'generaltable admintable');
        $this->set_attribute('id', $id);

        // Column definition.
        $columns = [
                'title',
                'executable',
                'originalname',
                'path',
                'dependencies',
                'visible',
                'uses',
                'actions',
        ];

        if ($hiddencolumns) {
            $columns = array_values(array_diff($columns, $hiddencolumns));
        }

        $headers = array_map(fn($column) => get_string($column, 'local_sebprogram'), $columns);

        $this->define_columns($columns);
        $this->define_headers($headers);

        if ($sortable) {
            $this->sortable(true, 'title');
            if (in_array('action', $columns)) {
                $this->no_sorting('actions');
            }
        }

        $this->setup();
    }

    /**
     * Set Course module id.
     *
     * @param int $returncmid Course module id of the activity to continue editing after returning
     */
    public function set_returncmid(int $returncmid) {
        $this->returncmid = $returncmid;
    }

    /**
     * Display title column.
     *
     * @param \local_sebprogram\program $data Program for this row.
     * @return string   Program title
     */
    protected function col_title(program $data): string {
        return $data->get('title');
    }


    /**
     * Display executable column.
     *
     * @param \local_sebprogram\program $data Program for this row.
     * @return string
     */
    protected function col_executable(program $data): string {
        return $data->get('executable');
    }

    /**
     * Display originalname column.
     *
     * @param \local_sebprogram\program $data Program for this row.
     * @return string
     */
    protected function col_originalname(program $data): string {
        return $data->get('originalname');
    }

    /**
     * Display path column.
     *
     * @param \local_sebprogram\program $data Program for this row.
     * @return string
     */
    protected function col_path(program $data): string {
        return $data->get('path');
    }

    /**
     * Display visible column.
     *
     * @param \local_sebprogram\program $data Program for this row.
     * @return string
     */
    protected function col_visible(program $data): string {
        return $data->get('visible') ? get_string('yes') : get_string('no');
    }

    /**
     * Display uses column.
     *
     * @param \local_sebprogram\program $data Program for this row.
     * @return string
     */
    protected function col_uses(program $data): string {
        $url = new \moodle_url('/local/sebprogram/modules.php', ['id' => $data->get('id'), 'returncmid' => $this->returncmid]);
        return \html_writer::link($url, $data->get('uses'));
    }

    /**
     * Display dependecies column.
     *
     * @param \local_sebprogram\program $data Program for this row.
     * @return string
     */
    protected function col_dependencies(program $data): string {

        $dependencies = $data->get_dependencies();

        $html = '';
        foreach ($dependencies as $program) {
            if ($this->is_downloading()) {
                if (!empty($html)) {
                    $html .= ',';
                }
                $html .= $program->get('title');
            } else {
                $html .= \html_writer::div(\html_writer::tag('strong', $program->get('title')));
            }
        }
        return $html;
    }

    /**
     * Display actions column.
     *
     * @param \local_sebprogram\program $data Program for this row.
     * @return string
     */
    protected function col_actions(program $data): string {
        return implode('&nbsp;', program_manager::get_action_icons($data, $this->returncmid));
    }

    /**
     * Override default implementation to display a more meaningful information to the user.
     *
     * @return void.
     */
    public function print_nothing_to_display(): void {
        global $OUTPUT;

        echo $OUTPUT->heading(get_string('nothingtodisplay', 'local_sebprogram'), 3);
    }


    /**
     * Sets the programs to display in the table.
     *
     * @param \local_sebprogram\program[] $programs An array with programs.
     */
    public function display(array $programs) {

        $sortcolumns = $this->get_sort_columns();

        uasort($programs, function ($a, $b) use ($sortcolumns) {
            $result = 0;
            foreach ($sortcolumns as $columnname => $order) {
                if ('dependencies' == $columnname) {
                    $dependencies = array_map(function ($program) {
                        return $program->get('title');
                    }, $a->get_dependencies());
                    sort($dependencies);
                    $valuea = implode(',', $dependencies);

                    $dependencies = array_map(function ($program) {
                        return $program->get('title');
                    }, $b->get_dependencies());
                    sort($dependencies);
                    $valueb = implode(',', $dependencies);
                } else {
                    $valuea = $a->get($columnname);
                    $valueb = $b->get($columnname);
                }
                if ($order == SORT_ASC) {
                    $result = strcmp($valuea, $valueb);
                } else {
                    $result = strcmp($valueb, $valuea);
                }

                if ($result <> 0) {
                    break;
                }
            }
            return $result;
        });

        foreach ($programs as $program) {
            $classname = (!$program->get('visible') ? 'dimmed_text' : '');
            $this->add_data_keyed($this->format_row($program), $classname);
        }
        $this->finish_output();
    }
}
